var tweeeeeeeets = [
  {
    created_at: 'Fri Mar 27 17:13:27 +0000 2015',
    id: 581504317309489200,
    id_str: '581504317309489152',
    text: 'RT @WeAreHighRoad: Our own @petetasker explains how a mobile friendly site gets you in Google\'s good books http://t.co/gxdPV14TDv http://t.…',
    source: '<a href="https://about.twitter.com/products/tweetdeck" rel="nofollow">TweetDeck</a>',
    truncated: false,
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: null,
    in_reply_to_user_id_str: null,
    in_reply_to_screen_name: null,
    user: {
      id: 72562996,
      id_str: '72562996',
      name: 'Peter Tasker',
      screen_name: 'petetasker',
      location: 'Ottawa Ontario Canada',
      profile_location: null,
      description: 'Programmer in Ottawa Canada. Husband, Father. Loves my wife, daughter, son and code.',
      url: 'http://t.co/GBegnVucjC',
      entities: {
        url: [Object],
        description: [Object]
      },
      protected: false,
      followers_count: 187,
      friends_count: 522,
      listed_count: 22,
      created_at: 'Tue Sep 08 14:17:26 +0000 2009',
      favourites_count: 8,
      utc_offset: -18000,
      time_zone: 'Quito',
      geo_enabled: true,
      verified: false,
      statuses_count: 1186,
      lang: 'en',
      contributors_enabled: false,
      is_translator: false,
      is_translation_enabled: false,
      profile_background_color: '0F0F0F',
      profile_background_image_url: 'http://pbs.twimg.com/profile_background_images/438396696481902592/mGyLk0mA.jpeg',
      profile_background_image_url_https: 'https://pbs.twimg.com/profile_background_images/438396696481902592/mGyLk0mA.jpeg',
      profile_background_tile: false,
      profile_image_url: 'http://pbs.twimg.com/profile_images/560878004570570752/-cqYgHk5_normal.jpeg',
      profile_image_url_https: 'https://pbs.twimg.com/profile_images/560878004570570752/-cqYgHk5_normal.jpeg',
      profile_banner_url: 'https://pbs.twimg.com/profile_banners/72562996/1403796906',
      profile_link_color: '3476A8',
      profile_sidebar_border_color: 'FFFFFF',
      profile_sidebar_fill_color: 'A0C5C7',
      profile_text_color: '333333',
      profile_use_background_image: true,
      default_profile: false,
      default_profile_image: false,
      following: false,
      follow_request_sent: false,
      notifications: false
    },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    retweeted_status: {
      created_at: 'Fri Mar 27 17:12:50 +0000 2015',
      id: 581504161474224100,
      id_str: '581504161474224128',
      text: 'Our own @petetasker explains how a mobile friendly site gets you in Google\'s good books http://t.co/gxdPV14TDv http://t.co/F9rYOv8DhC',
      source: '<a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>',
      truncated: false,
      in_reply_to_status_id: null,
      in_reply_to_status_id_str: null,
      in_reply_to_user_id: null,
      in_reply_to_user_id_str: null,
      in_reply_to_screen_name: null,
      user: {
        id: 105249723,
        id_str: '105249723',
        name: 'High Road',
        screen_name: 'WeAreHighRoad',
        location: 'North America',
        profile_location: null,
        description: 'We are High Road, the most agile and committed team of communicators on the planet. Living for killer ideas. Dying to deliver. #WeMakeItPersonal',
        url: 'http://t.co/ok42CNZb22',
        entities: [Object],
        protected: false,
        followers_count: 3694,
        friends_count: 1342,
        listed_count: 190,
        created_at: 'Fri Jan 15 20:39:15 +0000 2010',
        favourites_count: 414,
        utc_offset: -18000,
        time_zone: 'Central Time (US & Canada)',
        geo_enabled: true,
        verified: false,
        statuses_count: 3488,
        lang: 'en',
        contributors_enabled: false,
        is_translator: false,
        is_translation_enabled: false,
        profile_background_color: 'F89728',
        profile_background_image_url: 'http://pbs.twimg.com/profile_background_images/441960394312019968/CnoUUmpD.jpeg',
        profile_background_image_url_https: 'https://pbs.twimg.com/profile_background_images/441960394312019968/CnoUUmpD.jpeg',
        profile_background_tile: false,
        profile_image_url: 'http://pbs.twimg.com/profile_images/1834422250/HRC_Twitter_Logo_normal.jpg',
        profile_image_url_https: 'https://pbs.twimg.com/profile_images/1834422250/HRC_Twitter_Logo_normal.jpg',
        profile_banner_url: 'https://pbs.twimg.com/profile_banners/105249723/1415285319',
        profile_link_color: '0084B4',
        profile_sidebar_border_color: 'FFFFFF',
        profile_sidebar_fill_color: 'DEDEDE',
        profile_text_color: '333333',
        profile_use_background_image: false,
        default_profile: false,
        default_profile_image: false,
        following: false,
        follow_request_sent: false,
        notifications: false
      },
      geo: null,
      coordinates: null,
      place: null,
      contributors: null,
      retweet_count: 2,
      favorite_count: 1,
      entities: {
        hashtags: [],
        symbols: [],
        user_mentions: [Object],
        urls: [Object],
        media: [Object]
      },
      extended_entities: {media: [Object]},
      favorited: false,
      retweeted: false,
      possibly_sensitive: false,
      lang: 'en'
    },
    retweet_count: 2,
    favorite_count: 0,
    entities: {
      hashtags: [],
      symbols: [],
      user_mentions: [
        [Object],
        [Object]
      ],
      urls: [[Object]],
      media: [[Object]]
    },
    extended_entities: {media: [[Object]]},
    favorited: false,
    retweeted: false,
    possibly_sensitive: false,
    lang: 'en'
  },
  {
    created_at: 'Mon Mar 23 21:05:43 +0000 2015',
    id: 580113214760984600,
    id_str: '580113214760984576',
    text: 'Arguing with @nodejs on the bus home from work. #notwinning.',
    source: '<a href="https://about.twitter.com/products/tweetdeck" rel="nofollow">TweetDeck</a>',
    truncated: false,
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: null,
    in_reply_to_user_id_str: null,
    in_reply_to_screen_name: null,
    user: {
      id: 72562996,
      id_str: '72562996',
      name: 'Peter Tasker',
      screen_name: 'petetasker',
      location: 'Ottawa Ontario Canada',
      profile_location: null,
      description: 'Programmer in Ottawa Canada. Husband, Father. Loves my wife, daughter, son and code.',
      url: 'http://t.co/GBegnVucjC',
      entities: {
        url: [Object],
        description: [Object]
      },
      protected: false,
      followers_count: 187,
      friends_count: 522,
      listed_count: 22,
      created_at: 'Tue Sep 08 14:17:26 +0000 2009',
      favourites_count: 8,
      utc_offset: -18000,
      time_zone: 'Quito',
      geo_enabled: true,
      verified: false,
      statuses_count: 1186,
      lang: 'en',
      contributors_enabled: false,
      is_translator: false,
      is_translation_enabled: false,
      profile_background_color: '0F0F0F',
      profile_background_image_url: 'http://pbs.twimg.com/profile_background_images/438396696481902592/mGyLk0mA.jpeg',
      profile_background_image_url_https: 'https://pbs.twimg.com/profile_background_images/438396696481902592/mGyLk0mA.jpeg',
      profile_background_tile: false,
      profile_image_url: 'http://pbs.twimg.com/profile_images/560878004570570752/-cqYgHk5_normal.jpeg',
      profile_image_url_https: 'https://pbs.twimg.com/profile_images/560878004570570752/-cqYgHk5_normal.jpeg',
      profile_banner_url: 'https://pbs.twimg.com/profile_banners/72562996/1403796906',
      profile_link_color: '3476A8',
      profile_sidebar_border_color: 'FFFFFF',
      profile_sidebar_fill_color: 'A0C5C7',
      profile_text_color: '333333',
      profile_use_background_image: true,
      default_profile: false,
      default_profile_image: false,
      following: false,
      follow_request_sent: false,
      notifications: false
    },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    retweet_count: 0,
    favorite_count: 0,
    entities: {
      hashtags: [[Object]],
      symbols: [],
      user_mentions: [[Object]],
      urls: []
    },
    favorited: false,
    retweeted: false,
    lang: 'en'
  }